version: "3.2"
services:
  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_APPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      node_net:
        ipv4_address: 172.29.1.4
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16

      
